version: '2'
services:
  postfix:
    image: patrickgardella/wildcard-postfix:latest
    expose:
    - "25"
    env_file:
      - ../../credentials-smtp.env
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
